[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "2ssqbT37ictHqKVyXvL8AVSrSEWB2HznkTFjxgq2skpF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/barnakhil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
